import {useEffect, useState} from 'react';
import {createPortal} from 'react-dom';
import {Plus, ChevronLeft, ChevronRight, CalendarDays, MessageSquare, FileText, ClipboardCheck, Settings, History, ArrowRight, Download, Upload, Users, Clock, Search, X, BookOpen, CheckCircle2} from 'lucide-react';
import {childName, childStatus, columnText, remarksText, localDate, offsetDate, combinedCommunication} from '../utils/communicationFlow';

const states={regular:'通常',waitlist:'キャンセル待ち',absent:'欠席'};
const dateLabel=value=>new Date(`${value}T12:00:00`).toLocaleDateString('ja-JP',{year:'numeric',month:'long',day:'numeric',weekday:'short'});
const displayText=value=>typeof value==='string'?value:value?JSON.stringify(value):'';
const progress=(report,id)=>report.dailyTable?.[id]?.sentChecked?'送信確認済':report.results?.[id]?.isCompleted?'入力完了':report.results?.[id]?.D?.trim()?'編集中':(report.messages?.[id] || []).length?'メモあり':'未入力';

function ChildOperation({child,row,staff,onSave,onRemove,onClose,onMemo,office,date,onDirty}){
 const [form,setForm]=useState({status:childStatus(child),transportTime:row.transportTime || '',endTime:row.endTime || '',pickupLocation:row.pickupLocation || '',assignedStaff:row.assignedStaff || ''});
 const [changed,setChanged]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{onDirty(changed);return()=>onDirty(false);},[changed,onDirty]);
 const change=(key,value)=>{setForm(previous=>({...previous,[key]:value}));setChanged(true);};
 const leave=()=>{if(!busy&&(!changed||window.confirm('保存していない変更を破棄して戻りますか？')))onClose();};
 const save=async()=>{setBusy(true);setError('');try{await onSave(child.id,form);setChanged(false);onClose();}catch(reason){setError(reason.message || '保存できませんでした。再試行してください。');}finally{setBusy(false);}};
 return createPortal(<div className="cw-sheet-backdrop"><section className="cw-sheet" role="dialog" aria-modal="true" aria-labelledby="child-operation-title">
  <header className="cw-sheet-top"><button onClick={leave} disabled={busy}><ChevronLeft size={20}/>業務へ戻る</button><span>予約V2内</span></header>
  <div className="cw-sheet-body"><p className="cw-eyebrow">Tree Kids Schedule / ツリー通信v2</p><h2 id="child-operation-title">出欠・送迎を変更</h2><h3>{childName(child)}</h3><p>{office?.name} ・ {dateLabel(date)}</p>
   <fieldset disabled={busy} className="cw-form-fields"><legend>この日の利用情報</legend>
    <div className="cw-field-card"><h3>当日の区分</h3><div className="cw-segments">{Object.entries(states).map(([key,label])=><button key={key} type="button" aria-pressed={form.status===key} onClick={()=>change('status',key)}>{label}</button>)}</div></div>
    <div className="cw-field-card"><h3>送迎情報</h3><div className="cw-two"><label>送迎時刻<input type="time" step="300" value={form.transportTime} onChange={e=>change('transportTime',e.target.value)}/></label><label>終了時刻<input type="time" step="300" value={form.endTime} onChange={e=>change('endTime',e.target.value)}/></label></div><label>迎え場所<input value={form.pickupLocation} onChange={e=>change('pickupLocation',e.target.value)} placeholder="学校・自宅など"/></label></div>
    <div className="cw-field-card"><h3>通信の担当</h3><label>担当スタッフ<select value={form.assignedStaff} onChange={e=>change('assignedStaff',e.target.value)}><option value="">担当なし</option>{form.assignedStaff&&!staff.some(s=>s.name===form.assignedStaff)&&<option>{form.assignedStaff}</option>}{staff.map(s=><option key={s.id} value={s.name}>{s.name}</option>)}</select></label><button type="button" onClick={()=>change('assignedStaff','')}>担当を解除</button><p className="cw-hint">挨拶がない通信には、担当者の挨拶を反映します。</p></div>
   </fieldset>
   {error&&<p className="cw-error" role="alert">{error}</p>}
   <button className="cw-wide" disabled={busy} onClick={()=>{if(!changed||window.confirm('変更を破棄してメモを開きますか？')){onClose();onMemo(child.id);}}}>学習・プログラム・備考のメモへ <ArrowRight size={18}/></button>
   {childStatus(child)!=='regular'&&<button className="cw-danger cw-wide" disabled={busy} onClick={async()=>{if(!window.confirm('この日の一覧から外します。児童マスターや過去の記録は削除しません。'))return;setBusy(true);try{await onRemove(child.id);onClose();}catch(reason){setError(reason.message);setBusy(false);}}}>当日の一覧から外す</button>}
  </div><footer className="cw-sheet-footer"><button className="cw-primary" disabled={busy||!changed} onClick={save}>{busy?'保存中…':'変更を保存して戻る'}</button><button disabled={busy} onClick={leave}>取消</button></footer>
 </section></div>,document.body);
}

function DailyLog({global,staff,onSave,onLoadWeek,onDirty}){
 const values=()=>({notice:displayText(global.notice),activities:displayText(global.activities),programs:global.programs || (global.programTitle||global.programSummary?[{title:global.programTitle || '',summary:global.programSummary || '',staff:global.programStaff || ''}]:[])});
 const [form,setForm]=useState(values),[baseline,setBaseline]=useState(global),[dirty,setDirty]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[active,setActive]=useState(0),[week,setWeek]=useState(null),[weekBusy,setWeekBusy]=useState(false);
 useEffect(()=>{if(!dirty){setForm(values());setBaseline(global);}},[global,dirty]);
 useEffect(()=>{onDirty(dirty);return()=>onDirty(false);},[dirty,onDirty]);
 const change=(key,value)=>{setForm(old=>({...old,[key]:value}));setDirty(true);setMessage('');};
 const updateProgram=(key,value)=>change('programs',form.programs.map((p,index)=>index===active?{...p,[key]:value}:p));
 const save=async()=>{setBusy(true);setError('');try{
  const patch={},expected={};for(const key of ['notice','activities','programs'])if(JSON.stringify(form[key])!==JSON.stringify(key==='programs'?(baseline.programs || (baseline.programTitle||baseline.programSummary?[{title:baseline.programTitle || '',summary:baseline.programSummary || '',staff:baseline.programStaff || ''}]:[])):displayText(baseline[key]))){patch[key]=form[key];expected[key]=baseline[key] ?? '';}
  if(Object.keys(patch).length)await onSave(patch,expected);setDirty(false);setMessage('日報とプログラムを保存しました。通信への差込み・書出しに反映されます。');
 }catch(reason){setError(reason.message || '保存できませんでした。入力を残しています。');}finally{setBusy(false);}};
 return <section className="cw-daily" id="guide-program"><div className="cw-section-heading"><div><p className="cw-eyebrow">当日の記録</p><h2>施設日報・本日のプログラム</h2></div><button className="cw-primary" disabled={!dirty||busy} onClick={save}>{busy?'保存中…':dirty?'変更を保存':'保存済み'}</button></div>
  {error&&<p className="cw-error" role="alert">{error}</p>}{message&&<p className="cw-success" role="status">{message}</p>}
  <div className="cw-daily-grid"><fieldset className="cw-card" disabled={busy}><legend>日報</legend><label>特記事項（事前の連絡）<textarea rows={6} value={form.notice} onChange={e=>change('notice',e.target.value)} placeholder="活動前に確認したいこと"/></label><label>共有事項（活動後の記録）<textarea rows={7} value={form.activities} onChange={e=>change('activities',e.target.value)} placeholder="一日の気づきや引継ぎ"/></label><p className="cw-hint">【共有】メモの新規投稿もここへ追記されます。メモの編集・削除は追記済みの文章に反映されません。</p></fieldset>
   <fieldset className="cw-card" disabled={busy}><legend>本日のプログラム</legend><div className="cw-program-tabs">{form.programs.map((program,index)=><button key={index} aria-pressed={active===index} onClick={()=>setActive(index)}>{index+1} {program.title || '名称未入力'}</button>)}<button onClick={()=>{change('programs',[...form.programs,{title:'',summary:'',staff:''}]);setActive(form.programs.length);}}><Plus size={17}/>追加</button></div>
    {form.programs[active]?<><label>プログラム名<input value={form.programs[active].title || ''} onChange={e=>updateProgram('title',e.target.value)}/></label><label>担当スタッフ<select value={form.programs[active].staff || ''} onChange={e=>updateProgram('staff',e.target.value)}><option value="">未指定</option>{form.programs[active].staff&&!staff.some(s=>s.name===form.programs[active].staff)&&<option>{form.programs[active].staff}</option>}{staff.map(s=><option key={s.id}>{s.name}</option>)}</select></label><label>詳細・手順<textarea rows={9} value={form.programs[active].summary || ''} onChange={e=>updateProgram('summary',e.target.value)}/></label><button className="cw-danger" onClick={()=>{if(window.confirm('このプログラムを日報から削除しますか？差込み済みのメモは残ります。')){change('programs',form.programs.filter((_,index)=>index!==active));setActive(0);}}}>このプログラムを削除</button></>:<div className="cw-empty">活動の名前・担当・内容を追加してください。</div>}
   </fieldset>
   <aside className="cw-card"><h3><History size={20}/>前7日の記録</h3><p className="cw-hint">選択日の前日から7日分を表示します。</p><button className="cw-wide" disabled={weekBusy} onClick={async()=>{setWeekBusy(true);try{setWeek(await onLoadWeek());}catch{setError('過去の記録を取得できませんでした。もう一度開いてください。');}finally{setWeekBusy(false);}}}>{weekBusy?'読込中…':'前7日の記録を開く'}</button>{week?.map(item=><details className="cw-week" key={item.date}><summary>{dateLabel(item.date)}</summary><h4>特記事項</h4><p>{displayText(item.report?.globalLog?.notice)||'記録なし'}</p><h4>共有事項</h4><p>{displayText(item.report?.globalLog?.activities)||'記録なし'}</p></details>)}</aside>
  </div><div className="cw-mobile-save"><button className="cw-primary cw-wide" disabled={busy||!dirty} onClick={save}>{busy?'保存中…':'日報とプログラムを保存'}</button></div>
 </section>;
}

export default function CommunicationWorkspace(props){
 const {report,attendance,staff,office,offices,date,staffName,columns,loading,busy,disabled,browserPreview,sharedStorage,isAdmin,portalMode=browserPreview,onSyncDay,onDate,onOffice,onEditor,onModal,onSaveChild,onRemoveChild,onSaveTable,onSaveGlobal,onLoadWeek,onCopy,onCopySelected,onDirtyChange,onLogout}=props;
 const [view,setView]=useState(props.initialView || 'record'),[search,setSearch]=useState(''),[filter,setFilter]=useState('all'),[childEdit,setChildEdit]=useState(null),[selected,setSelected]=useState([]),[preview,setPreview]=useState(false),[dirty,setDirty]=useState(false),[error,setError]=useState(''),[actionBusy,setActionBusy]=useState(false);
 const locked=loading||busy||disabled||actionBusy;
 const leave=action=>{if(locked)return;if(!dirty||window.confirm('保存していない変更を破棄して移動しますか？')){setDirty(false);onDirtyChange(false);action();}};
 useEffect(()=>{onDirtyChange(dirty);},[dirty,onDirtyChange]);
 useEffect(()=>{const tools=()=>setView('tools'),daily=()=>setView('daily');window.addEventListener('tree-tsushin:show-tools',tools);window.addEventListener('tree-tsushin:show-daily',daily);return()=>{window.removeEventListener('tree-tsushin:show-tools',tools);window.removeEventListener('tree-tsushin:show-daily',daily);};},[]);
 const run=async action=>{setActionBusy(true);setError('');try{await action();}catch(reason){setError(reason.message || '操作を完了できませんでした。再試行してください。');}finally{setActionBusy(false);}};
 const children=report.children.filter(c=>!c.isPlaceholder).slice().sort((a,b)=>(report.dailyTable[a.id]?.transportTime || '99:99').localeCompare(report.dailyTable[b.id]?.transportTime || '99:99'));
 const visible=children.filter(c=>`${childName(c)} ${c.kana || ''} ${c.lastNameKana || ''} ${c.firstNameKana || ''}`.includes(search)).filter(c=>filter==='all'||filter==='regular'&&childStatus(c)==='regular'||filter==='waitlist'&&childStatus(c)==='waitlist'||filter==='absent'&&childStatus(c)==='absent'||filter==='todo'&&!report.results[c.id]?.isCompleted||filter==='done'&&report.results[c.id]?.isCompleted||filter==='unsent'&&!report.dailyTable[c.id]?.sentChecked);
 const tools=[...(sharedStorage&&isAdmin?[['legacyArchive','移行した旧データ・照合保留',History,'原文を読取り専用で確認']]:[]),['operations','出欠・送迎',Users,'当日の区分、時刻、迎え場所、担当'],['daily','施設日報・プログラム',FileText,'全体の記録と前7日の振返り'],['attendance','スタッフ勤務',Clock,'勤務区分・開始時刻・終了時刻'],['settings','入力設定',Settings,'挨拶・タグ・定型文・OKワード'],['csv','送迎CSV取込み',Upload,'照合・差分を確認して反映'],['restore','バックアップ復元',History,'対象日と児童を選んで復元'],['export','書出し・Excel・印刷',Download,'CSV保存と日誌の作成'],['logs','変更履歴',History,'変更前後の比較と旧値コピー'],['help','使い方',BookOpen,'操作ガイドと入力の流れ'],['update','更新のお知らせ',CheckCircle2,'変更点と画面の案内']];
 return <main className="cw-workspace" inert={props.interactionBlocked || childEdit || preview ? '' : undefined}>
  {!portalMode&&<div className="cw-standalone"><img src="/logo.png" alt="Tree Kids School（ツリーキッズスクール）"/><strong>ツリー通信v2</strong><button onClick={()=>leave(onLogout)}>ログアウト</button></div>}
  <header className="cw-title"><div><p className="cw-eyebrow">{portalMode?'Tree Kids Schedule / スタッフ':'ローカル開発環境'}</p><h1>ツリー通信<span>v2</span></h1></div><span className="cw-storage">{sharedStorage?'予約V2に共有保存':browserPreview?'このブラウザーに仮保存・未共有':'ローカルエミュレーター'}</span></header>
  <nav className="cw-nav" aria-label="ツリー通信のメニュー">{[['record','今日の記録'],['communication','通信を整える'],['logs','履歴'],['tools','業務・設定']].map(([key,label])=><button key={key} aria-current={view===key||key==='tools'&&['operations','daily'].includes(view)?'page':undefined} onClick={()=>leave(()=>key==='logs'?onModal('logs'):setView(key))}>{label}</button>)}</nav>
  <div className="cw-context"><div className="cw-date"><button title="前日" disabled={locked} onClick={()=>leave(()=>onDate(offsetDate(date,-1)))}><ChevronLeft size={20}/></button><button id="guide-date-picker" disabled={locked} onClick={()=>leave(()=>onModal('calendar'))}><CalendarDays size={18}/>{dateLabel(date)}</button><button title="翌日" disabled={locked} onClick={()=>leave(()=>onDate(offsetDate(date,1)))}><ChevronRight size={20}/></button><button disabled={locked||date===localDate()} onClick={()=>leave(()=>onDate(localDate()))}>今日</button></div><label className="cw-office">事業所<select aria-label="事業所" disabled={locked} value={office?.id || ''} onChange={e=>leave(()=>onOffice(e.target.value))}>{offices.map(item=><option value={item.id} key={item.id}>{item.name}</option>)}</select></label><span className="cw-staff">{staffName}</span></div>
  {error&&<p className="cw-error" role="alert">{error}<button onClick={()=>setError('')}>閉じる</button></p>}
  {loading?<div className="cw-loading">この日の記録を読み込んでいます…</div>:<>
  {view==='tools'?<section><div className="cw-section-heading"><h2>業務・設定</h2><p>毎日の記録を支える操作</p></div><div className="cw-tools">{tools.map(([key,label,Icon,hint])=><button key={key} id={`guide-${key}`} onClick={()=>leave(()=>['operations','daily'].includes(key)?setView(key):onModal(key))}><Icon size={24}/><span><strong>{label}</strong><small>{hint}</small></span><ArrowRight size={19}/></button>)}</div></section>:view==='daily'?<><button className="cw-back" onClick={()=>leave(()=>setView('tools'))}><ChevronLeft size={18}/>業務・設定へ戻る</button><DailyLog global={report.globalLog} staff={staff} onSave={onSaveGlobal} onLoadWeek={onLoadWeek} onDirty={setDirty}/></>:<>
   <section className="cw-stats" aria-label="本日の進み具合">{(view==='operations'?[['通常',children.filter(c=>childStatus(c)==='regular').length,'regular'],['キャンセル待ち',children.filter(c=>childStatus(c)==='waitlist').length,'waitlist'],['欠席',children.filter(c=>childStatus(c)==='absent').length,'absent']]:[['今日の児童',children.length,'all'],['入力完了',children.filter(c=>report.results[c.id]?.isCompleted).length,'done'],['送信未確認',children.filter(c=>!report.dailyTable[c.id]?.sentChecked).length,'unsent']]).map(([label,count,key])=><button key={key} onClick={()=>setFilter(filter===key?'all':key)} aria-pressed={filter===key}><span>{label}</span><strong>{count}<small>名</small></strong></button>)}</section>
   <section className="cw-card cw-list"><div className="cw-section-heading"><div><p className="cw-eyebrow">{view==='operations'?'出欠・送迎・担当':view==='communication'?'一人ひとりの言葉を整える':'小さな気づきを、その場で'}</p><h2>{view==='operations'?'当日の業務':view==='communication'?'通信を整える':'今日の記録'}</h2></div><div className="cw-roster-actions">{sharedStorage&&<button disabled={locked} onClick={()=>run(onSyncDay)}>予約名簿を取り込む</button>}<button id="guide-add-child" className="cw-primary" disabled={locked} onClick={()=>onModal('add')}><Plus size={18}/>児童を追加</button></div></div>
    <div className="cw-list-tools"><label className="cw-search"><Search size={18}/><input aria-label="児童を検索" placeholder="児童を検索" value={search} onChange={e=>setSearch(e.target.value)}/></label><select aria-label="表示する記録" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">すべて</option><option value="todo">入力未完了</option><option value="done">入力完了</option><option value="unsent">送信未確認</option><option value="regular">通常</option><option value="waitlist">キャンセル待ち</option><option value="absent">欠席</option></select><button disabled={locked} onClick={()=>setView(view==='operations'?'record':'operations')}>{view==='operations'?'記録の一覧へ':'出欠・送迎を確認'}</button></div>
    {visible.length===0?<div className="cw-empty"><MessageSquare size={32}/><h3>{children.length?'条件に合う児童がいません':'この日の記録を始めましょう'}</h3><p>{children.length?'検索や絞込みを変更してください。':'児童を追加すると、メモ・通信・送迎情報を記録できます。'}</p>{!children.length&&<p>{sharedStorage?'「予約名簿を取り込む」で、予約V2の当日児童を追加できます。':'予約名簿の取込みは、共有保存版で利用できます。'}</p>}</div>:<div className={`cw-records ${view==='operations'?'cw-records-operations':''}`}>
     {view==='operations'&&<div className="cw-table-head"><span>児童</span><span>学習・プログラム</span><span>送迎・終了</span><span>迎え場所・担当</span><span>備考・操作</span></div>}
     {visible.map(child=>{const row=report.dailyTable[child.id] || {},result=report.results[child.id] || {},messages=report.messages[child.id] || [],state=progress(report,child.id);return <article className="cw-child" key={child.id}>
      <div className="cw-child-identity"><span className={`cw-avatar ${childStatus(child)}`}>{childName(child).slice(0,1)}</span><div><h3>{childName(child)}</h3>{child.identityReview&&<span className="cw-identity-review"><strong>照合保留</strong><span>{child.identityReview==="birth-conflict"?"生年月日相違":"旧データの対応確認が必要です"}</span></span>}<span className={`cw-status ${childStatus(child)}`}>{states[childStatus(child)]}</span>{child.grade&&<small>{child.grade}</small>}</div><span className={`cw-progress ${result.isCompleted?'complete':''}`}>{state}</span></div>
      {view==='operations'?<><div className="cw-derived"><span>学習</span><p>{columnText(messages,'learning',columns)||'—'}</p><span>プログラム</span><p>{columnText(messages,'program',columns)||'—'}</p></div><div className="cw-transport"><span>送迎 <strong>{row.transportTime||'未設定'}</strong></span><span>終了 <strong>{row.endTime||'未設定'}</strong></span></div><div className="cw-derived"><span>迎え場所</span><p>{row.pickupLocation||'未設定'}</p><span>担当</span><p>{row.assignedStaff||'担当なし'}</p></div><div className="cw-child-actions"><p className="cw-note">{remarksText(messages,columns,row)||'備考なし'}</p><button disabled={locked} onClick={()=>setChildEdit(child.id)}>出欠・送迎を変更</button><button disabled={locked} onClick={()=>onEditor(child.id,'memo')}>メモへ</button></div></>:<>
       <div className="cw-child-content">{view==='communication'?<><p className="cw-body-preview">{result.D || '通信本文はまだありません。メモを選んで文章を整えましょう。'}</p>{result.futurePlan&&<p className="cw-future"><strong>今後の予定</strong>{result.futurePlan}</p>}</>:<><span className="cw-hint">{messages.length}件のメモ ・ 担当 {row.assignedStaff || '未設定'}</span><p className="cw-body-preview">{messages.at(-1)?.text || '今日の気づきや、できたことを残しましょう。'}</p></>}</div>
       <div className="cw-child-actions"><button className="cw-primary" disabled={locked} onClick={()=>onEditor(child.id,view==='communication'?'tree':'memo')}><MessageSquare size={17}/>{view==='communication'?'通信を編集':'メモを書く'}</button>{view==='record'?<button disabled={locked} onClick={()=>onEditor(child.id,'tree')}>通信を整える</button>:<><button disabled={locked||!result.D?.trim()} onClick={()=>run(()=>onCopy(child.id))}>コピー</button><label className="cw-check"><input type="checkbox" checked={!!row.sentChecked} disabled={locked} onChange={e=>run(()=>onSaveTable(child.id,{sentChecked:e.target.checked}))}/>手動送信確認</label><label className="cw-check"><input type="checkbox" checked={selected.includes(child.id)} disabled={!result.D?.trim()} onChange={e=>setSelected(old=>e.target.checked?[...old,child.id]:old.filter(id=>id!==child.id))}/>結合コピーに選択</label></>}</div>
      </>}
     </article>;})}
    </div>}
    <p className="cw-list-foot">{view==='operations'?'学習・プログラム・備考はメモのタグ設定から表示します。送迎時刻順です。':'入力完了・コピー・手動送信確認は別の状態です。コピーだけではLINEに送信されません。'}</p>
   </section>
   {view==='communication'&&<div className="cw-copy-bar"><span>{selected.length}名を選択</span><button disabled={locked||!selected.length} onClick={()=>setSelected([])}>選択を解除</button><button className="cw-primary" disabled={locked||!selected.length} onClick={()=>setPreview(true)}>結合する本文を確認</button></div>}
   <div className="cw-quick-links"><button onClick={()=>leave(()=>setView('daily'))}><FileText size={18}/>施設日報・プログラム</button><button id="guide-attendance" onClick={()=>onModal('attendance')}><Clock size={18}/>スタッフ勤務 <small>{Object.values(attendance).filter(a=>a.type==='work').length}名 出勤登録</small></button><button onClick={()=>setView('tools')}><Settings size={18}/>業務・設定</button></div>
  </>}
  </>}
  <footer className="cw-footer">Tree Kids Schedule / ツリー通信v2 <span>{sharedStorage?'共有保存 · 保護者公開は未接続':browserPreview?'ブラウザー内の仮保存':'開発用の記録'}</span></footer>
  {childEdit&&report.children.find(c=>c.id===childEdit)&&<ChildOperation child={report.children.find(c=>c.id===childEdit)} row={report.dailyTable[childEdit] || {}} staff={staff} date={date} office={office} onSave={onSaveChild} onRemove={onRemoveChild} onClose={()=>setChildEdit(null)} onMemo={id=>onEditor(id,'memo')} onDirty={setDirty}/>}
  {preview&&createPortal(<div className="cw-sheet-backdrop"><section className="cw-sheet" role="dialog" aria-modal="true" aria-labelledby="copy-title"><header className="cw-sheet-top"><h2 id="copy-title">選択した児童の結合コピー</h2><button onClick={()=>setPreview(false)} aria-label="閉じる"><X size={22}/></button></header><div className="cw-sheet-body"><p>同じ姓の児童は名前をまとめ、同じ本文は重複を省きます。送信先と本文を確認してください。</p><textarea readOnly rows={16} aria-label="コピーする本文" value={combinedCommunication(report.children,report.results,selected)}/>{error&&<p role="alert" className="cw-error">{error}</p>}</div><footer className="cw-sheet-footer"><button className="cw-primary" disabled={actionBusy} onClick={()=>run(async()=>{await onCopySelected(selected);setPreview(false);setSelected([]);})}>この内容をコピー</button></footer></section></div>,document.body)}
 </main>;
}
